### ISSUE TITLE
Other ways to support XOAuth2

### ISSUE THREAD

**Issue by shackra** [emersion/go-sasl#20]
hi!

Saw the [PR removing this authentication mechanism](https://github.com/emersion/go-sasl/issues/18) and wonder if there are other ways to support that without necessarily copy-pasting the removed file before that PR (i.e.: third-party libraries that you would recommend instead)

**Comment by foxcpp** [comment]
Quick search on GitHub did not reveal any well-written SASL libraries supporting XOAUTH2. I believe copy-pasting the file is the best way.
